export const tools = [{
  key: 'base64',
  title: 'Tools.Base64.Name',
  description: 'Tools.Base64.Description',
  href: '/tools/base64'
}, {
  key: 'time',
  title: 'Tools.Time.Name',
  description: 'Tools.Time.Description',
  href: '/tools/time'
}, {
  key: 'mongodb',
  title: 'Tools.MongoDB.Name',
  description: 'Tools.MongoDB.Description',
  href: '/tools/mongodb'
}, {
  key: 'radix',
  title: 'Tools.Radix.Name',
  description: 'Tools.Radix.Description',
  href: '/tools/radix'
}, {
  key: 'jwt',
  title: 'Tools.JWT.Name',
  description: 'Tools.JWT.Description',
  href: '/tools/jwt'
 }, {
  key: 'useragent',
  title: 'Tools.UserAgent.Name',
  description: 'Tools.UserAgent.Description',
  href: '/tools/useragent'
 }];
