export const tools = [{
  key: 'base32',
  title: 'Tools.Base32.Name',
  description: 'Tools.Base32.Description',
  href: '/tools/base32'
}, {
  key: 'base64',
  title: 'Tools.Base64.Name',
  description: 'Tools.Base64.Description',
  href: '/tools/base64'
}, {
  key: 'url',
  title: 'Tools.URL.Name',
  description: 'Tools.URL.Description',
  href: '/tools/url'
}, {
  key: 'time',
  title: 'Tools.Time.Name',
  description: 'Tools.Time.Description',
  href: '/tools/time'
}, {
  key: 'mongodb',
  title: 'Tools.MongoDB.Name',
  description: 'Tools.MongoDB.Description',
  href: '/tools/mongodb'
}, {
  key: 'radix',
  title: 'Tools.Radix.Name',
  description: 'Tools.Radix.Description',
  href: '/tools/radix'
}, {
  key: 'jwt',
  title: 'Tools.JWT.Name',
  description: 'Tools.JWT.Description',
  href: '/tools/jwt'
 }, {
  key: 'hash',
  title: 'Tools.Hash.Name',
  description: 'Tools.Hash.Description',
  href: '/tools/hash'
 }, {
  key: 'qrcode',
  title: 'Tools.QRCode.Name',
  description: 'Tools.QRCode.Description',
  href: '/tools/qrcode'
 }, {
  key: 'totp',
  title: 'Tools.TOTP.Name',
  description: 'Tools.TOTP.Description',
  href: '/tools/totp'
 }, {
  key: 'useragent',
  title: 'Tools.UserAgent.Name',
  description: 'Tools.UserAgent.Description',
  href: '/tools/useragent'
 }];
